### ISSUE TITLE
As a user I would like the ability to sign into the same account with an email and password or using the Google Sign In services.

### ISSUE THREAD

**Issue by Vektorised** [GitReadyTeam5/Diamond-Project08-5a#12]
Point Value: 3

Acceptance Criteria:
- Users should be able to specify a password during the sign up process with Google.
- Users should be able to sign in with either an email and password or using Google Sign in.

Tasks: 
- [x]  Create a new page within the sign up flow that gets a password to save alongside a user account.
- [x]  Ensure both a Google unique ID and email and password are stored in the database for a user.

**Comment by GitReadyMao** [comment]
We have the Google ID and email stored within the database. However, no password as upon signing in with Google, it automatically logs in without a password needed.

**Comment by shreya-kota** [comment]
Currently in the process of developing a signup page where a user can attach a password to their account

**Comment by GitReadyMao** [comment]
Removed the password page as it creates redundancy
